# Generated by Django 4.1.7 on 2023-03-25 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_orderitem_image_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postalCoode',
            new_name='postalCode',
        ),
    ]
