# Generated by Django 4.1.7 on 2023-03-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/images/placeholder.png', null=True, upload_to=''),
        ),
    ]
